### ISSUE TITLE
Failed writing body

### ISSUE THREAD

**Issue by Teicu** [liamg/scout#1]
Hi 

I try to install this script on Mac os but I always get the same error. Can you help me? Thanks 

 % curl -s "https://raw.githubusercontent.com/liamg/scout/master/scripts/install.sh" | bash
Determining platform...
Finding latest release...
bash: line 8: jq: command not found
(23) Failed writing body

**Comment by liamg** [comment]
Sure, you need to install `jq`:

On Mac:
```
brew install jq
```

**Comment by Teicu** [comment]
Hi 

Has worked after I installed that

Thank you very much.

have a good day
