### ISSUE TITLE
Enhancement: An argument/flag to filter out HTTP status codes or show only some in the output that are specified after the flag

### ISSUE THREAD

**Issue by Umarovm** [liamg/scout#11]
Like filtering the output so that only urls that return code 200 show in the output:
`scout url --filter 200`

**Comment by liamg** [comment]
Hey @Umarovm - you can use the ` --status-codes` flag and supply a comma separated list of status codes you'd like to include e.g. ` --status-codes 200,302` - I'll add this to the README too!
