### ISSUE TITLE
When scout gets to ".backup.html", it stops (using the default wordlist).

### ISSUE THREAD

**Issue by Umarovm** [liamg/scout#12]
For example, when using the default wordlist to scan https://www.apple.com/, it gets stuck on:
`Checking https://www.apple.com/.backup.html...`

I've encountered this bug (I think it's a bug) with several other websites too and it only stops on .backup.html for some reason, but I suspect it's because there are two periods in ".backup.html" which makes it unique from all the other pages in the wordlist.

**Comment by liamg** [comment]
Interesting - I haven't encountered this but I'll take a look!

**Comment by liamg** [comment]
This should now be resolved with the latest version :+1:
