### ISSUE TITLE
Problem installing assets

### ISSUE THREAD

**Issue by stevemeltzer1** [liamg/scout#15]
Hi there - Thanks for the work on this project. 

I'm a bit of a noob and I have googled this issue many times. I can't get the file installation to work, so I run into a command not found error. Can you help?

Thanks!
![2020-09-07_11-01-33](https://user-images.githubusercontent.com/5572529/92400353-cde3c200-f0f9-11ea-817a-31742e071db9.png)

**Comment by liamg** [comment]
Hi @stevemeltzer1 - it looks like you have missed the `| bash` off the end of the install command - you need the full:
```
curl -s "https://raw.githubusercontent.com/liamg/scout/master/scripts/install.sh" | bash
```
