### ISSUE TITLE
License statement

### ISSUE THREAD

**Issue by fabaff** [liamg/scout#17]
To be able to create distribution packages, the source should have a license statement and a LICENSE file should be part of the source.

Thanks in advance to add it.

**Comment by liamg** [comment]
Hi @fabaff - good spot, I've added the license now (https://github.com/liamg/scout/pull/18)

Thanks :+1:

**Comment by fabaff** [comment]
Thanks.

Package review is now [open](https://bugzilla.redhat.com/show_bug.cgi?id=1882899) for the Fedora Package Collection.
